[package]
name = 'mindao'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
mindao = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }
